// DROPDOWN MENU / SIDEBAR / MOBILE MENU / FILTERBAR
export const TOGGLE_DROPDOWN = "TOGGLE_DROPDOWN";
export const TOGGLE_MOBILE_MENU = "TOGGLE_MOBILE_MENU";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_FILTERBAR = "TOGGLE_FILTERBAR";

// ALERT
export const SHOW_SUCCESS_ALERT = "SHOW_SUCCESS_ALERT";
export const SHOW_ERROR_ALERT = "SHOW_ERROR_ALERT";
export const SHOW_PENDDING_ALERT = "SHOW_PENDDING_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

/// REGISTER
export const REGISTER_BEGGING = "REGISTER_BEGGING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

/// LOGIN
export const LOGIN_BEGGING = "LOGIN_BEGGING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

// SHOW CURRENT USER
export const SHOW_CURRENT_USER_BEGGING = "SHOW_CURRENT_USER_BEGGING";
export const SHOW_CURRENT_USER_SUCCESS = "SHOW_CURRENT_USER_SUCCESS";
export const SHOW_CURRENT_USER_FAILED = "SHOW_CURRENT_USER_FAILED";

// UPDATE USER INFORMATIONS
export const UPDATE_USER_BEGGING = "UPDATE_USER_BEGGING";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

// CHANGE PASSWORD
export const CHANGE_PASSWORD_BEGGING = "CHANGE_PASSWORD_BEGGING";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

// LOGOUT
export const LOGOUT_BEGGING = "LOGOUT_BEGGING";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

//************ PRODUCTS ACTIONS *************** //
// UPLOAD IMAGE
export const UPLOAD_PRODUCT_IMAGE_BEGGING = "UPLOAD_PRODUCT_IMAGE_BEGGING";
export const UPLOAD_PRODUCT_IMAGE_SUCCESS = "UPLOAD_PRODUCT_IMAGE_SUCCESS";
export const UPLOAD_PRODUCT_IMAGE_FAILED = "UPLOAD_PRODUCT_IMAGE_FAILED";
// CREATE PRODUCT
export const CRAETE_PRODUCT_BEGGING = "CRAETE_PRODUCT_BEGGING";
export const CRAETE_PRODUCT_SUCCESS = "CRAETE_PRODUCT_SUCCESS";
export const CRAETE_PRODUCT_FAILED = "CRAETE_PRODUCT_FAILED";
// FETCH ALL PRODUCTS
export const FETCH_ALL_PRODUCTS_BEGGING = "FATCH_ALL_PRODUCTS_BEGGING";
export const FETCH_ALL_PRODUCTS_SUCCESS = "FATCH_ALL_PRODUCTS_SUCCESS";
export const FETCH_ALL_PRODUCTS_FAILED = "FATCH_ALL_PRODUCTS_FAILED";
//FETCH FEATUED PRODUCTS
export const FETCH_FEATURED_PRODUCTS_BEGGING = "FATCH_FEATURED_PRODUCTS_BEGGING";
export const FETCH_FEATURED_PRODUCTS_SUCCESS = "FATCH_FEATURED_PRODUCTS_SUCCESS";
export const FETCH_FEATURED_PRODUCTS_FAILED = "FATCH_FEATURED_PRODUCTS_FAILED";
// DELETE PRODUCT
export const DELETE_PRODUCT_BEGGING = "DELETE_PRODUCT_BEGGING";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";
// UPDATE PRODUCT
export const UPDATE_PRODUCT_BEGGING = "UPDATE_PRODUCT_BEGGING";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";
// FETCH SINGLE PRODUCT
export const FETCH_SINGLE_PRODUCT_BEGGING = "FETCH_SINGLE_PRODUCT_BEGGING";
export const FETCH_SINGLE_PRODUCT_SUCCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
export const FETCH_SINGLE_PRODUCT_FAILED = "FETCH_SINGLE_PRODUCT_FAILED";
export const CLEAR_SINGLE_PRODUCT = "CLEAR_SINGLE_PRODUCT";
// SELECT SINGLE PRODUCT
export const SELECT_SINGLE_PRODUCT = "SELECT_SINGLE_PRODUCT";
// SELECT IMAGE
export const SELECT_IMAGE = "SELECT_IMAGE";
// SORT PRODUCTS
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const SET_SORT_PRODUCTS = "SET_SORT_PRODUCTS";

// FILTER PRODUCTS
export const SET_FILTER_PRODUCTS = "SET_FILTER_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";

// ADD TO CART CART
export const ADD_TO_CART_BEGGING = "ADD_TO_CART_BEGGING";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_BEGGING";

// SHOW USER CART
export const SHOW_USER_CART_BEGGING = "SHOW_USER_CART_BEGGING";
export const SHOW_USER_CART_SUCCESS = "SHOW_USER_CART_SUCCESS";
export const SHOW_USER_CART_FAILED = "SHOW_USER_CART_BEGGING";

// REMOVE CART
export const REMOVE_CART_BEGGING = "REMOVE_CART_BEGGING";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_FAILED = "REMOVE_CART_BEGGING";

// CLEAR CART
export const CLEAR_CART = "CLEAR_CART";

// REMOVE FROM CART
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";

// CALCULATE
export const CALCULATE_TOTAL = "CALCULATE_TOTAL";
export const CALCULATE_SUBTOTAL = "CALCULATE_SUBTOTAL";

// TOGGLE RAVIEW MODAL 
export const TOGGLE_REVIEW_MODAL='TOGGLE_REVIEW_MODAL'
// ADD REVIEW
export const ADD_REVIEW_BEGGING = "ADD_REVIEW_BEGGING";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_FAILED = "ADD_REVIEW_BEGGING";
// EDIT REVEIW
export const EDIT_REVIEW_BEGGING = "EDIT_REVIEW_BEGGING";
export const EDIT_REVIEW_SUCCESS = "EDIT_REVIEW_SUCCESS";
export const EDIT_REVIEW_FAILED = "EDIT_REVIEW_BEGGING";
// FETCH PRODUCT REVIEWS
export const FETCH_PRODUCT_REVIEWS_BEGGING = "FETCH_PRODUCT_REVIEWS_BEGGING";
export const FETCH_PRODUCT_REVEIWS_SUCCESS = "FETCH_PRODUCT_REVEIWS_SUCCESS";
export const FETCH_PRODUCT_REVEIWS_FAILED = "FETCH_PRODUCT_REVEIWS_BEGGING";
// FIND USER REVEIW
export const FIND_USER_REVIEW = "FIND_USER_REVIEW";
// SET CATEGORY 
export const SET_CATEGORY = "SET_CATEGORY";
// CLEAR FILTER PRODUCTS
export const CLEAR_FILTRED_PRODUCTS = "CLEAR_FILTRER_PRODUCTS";
// CREEATE ADRESS 
export const CREATE_ADRESS_BEGGING = "CREATE_ADRESS_BEGGING";
export const CREATE_ADRESS_SUCCESS = "CREATE_ADRESS_SUCCESS";
export const CREATE_ADRESS_FAILED = "CREATE_ADRESS_FAILED";
// FETCH ADRESS
export const FETCH_ADRESS_BEGGING = "FETCH_ADRESS_BEGGING";
export const FETCH_ADRESS_SUCCESS = "FETCH_ADRESS_SUCCESS";
export const FETCH_ADRESS_FAILED = "FETCH_ADRESS_FAILED";
// UPDATE ADRESS
export const UPDATE_ADRESS_BEGGING = "UPDATE_ADRESS_BEGGING";
export const UPDATE_ADRESS_SUCCESS = "UPDATE_ADRESS_SUCCESS";
export const UPDATE_ADRESS_FAILED = "UPDATE_ADRESS_FAILED";
// LOAD ALL COUNTRIES

export const LOAD_ALL_COUNTRIES_BEGGING = "LOAD_ALL_COUNTRIES_BEGGING";
export const LOAD_ALL_COUNTRIES_SUCCESS = "LOAD_ALL_COUNTRIES_SUCCESS";
export const LOAD_ALL_COUNTRIES_FAILED = "LOAD_ALL_COUNTRIES_FAILED";
// TOGGLE ADRESS MODAL
export const TOGGLE_ADRESS_MODAL = "TOGGLE_ADRESS_MODAL";
// CREATE ORDER 
export const CREATE_ORDER_BEGGING = "CREATE_ORDER_BEGGING";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED";
// FETCH USER ORDERS
export const FETCH_USER_ORDERS_BEGGING = "FETCH_USER_ORDERS_BEGGING";
export const FETCH_USER_ORDERS_SUCCESS = "FETCH_USER_ORDERS_SUCCESS";
export const FETCH_USER_ORDERS_FAILED = "FETCH_USER_ORDERS_FAILED";
// FETCH USER ORDERS
export const FETTCH_ALL_ORDERS_BEGGING = "FETTCH_ALL_ORDERS_BEGGING";
export const FETTCH_ALL_ORDERS_SUCCESS = "FETTCH_ALL_ORDERS_SUCCESS";
export const FETTCH_ALL_ORDERS_FAILED = "FETTCH_ALL_ORDERS_FAILED";

// CLEAR USER CART 
export const CLEAR_USER_CART_BEGGING = "CLEAR_USER_CART_BEGGING"
export const CLEAR_USER_CART_FAILED = "CLEAR_USER_CART_FAILED"
export const CLEAR_USER_CART_SUCCESS = "CLEAR_USER_CART_SUCCESS"

// EDIT STATUS
export const EDIT_STATUS_BEGGING = "EDIT_STATUS_BEGGING"
export const EDIT_STATUS_FAILED = "EDIT_STATUS_FAILED"
export const EDIT_STATUS_SUCCESS = "EDIT_STATUS_SUCCESS"

// FETCH ALL USERS
export const FETCH_ALL_USERS_BEGGING = "FETCH_ALL_USERS_BEGGING"
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS_FAILED"
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS"

// SEND SINGLE EMAIL 
export const SEND_SINGLE_EMAIL_BEGGING = "SEND_SINGLE_EMAIL_BEGGING"
export const SEND_SINGLE_EMAIL_FAILED = "SEND_SINGLE_EMAIL_FAILED"
export const SEND_SINGLE_EMAIL_SUCCESS = "SEND_SINGLE_EMAIL_SUCCESS"